<div class="card">
  <img class="card-img-top" src="holder.js/100px180/" alt="">
  <div class="card-body">
    <h4 class="card-title">Bienvenido</h4>
    <form action="<?= PUBLIC_PATH."login/loguear"?>" method="post">
        <div class="form-group">
          <label for="">Nombre de usuario</label>
          <input type="text" name="nombre" id="" class="form-control" placeholder="" aria-describedby="helpId">
        </div>
        <div class="form-group">
          <label for="">Contraseña</label>
          <input type="password" name="pass" id="" class="form-control" placeholder="" aria-describedby="helpId">
        </div>

        <input type="submit" value="Iniciar Sesión">
    </form>
  </div>
</div>